CREATE TABLE product (
  id                        CHAVE                    NOT NULL,
  id_supplier               CHAVE,
  id_manufacturer           CHAVE,
  id_category_default       CHAVE,
  id_shop_default           CHAVE                    NOT NULL,
  id_tax_rules_group        CHAVE                    NOT NULL,
  on_sale                   BOOLEAN                  NOT NULL,
  online_only               BOOLEAN                  NOT NULL,
  ean13                     CHARACTER VARYING(13),
  isbn                      CHARACTER VARYING(32),
  upc                       CHARACTER VARYING(12),
  ecotax                    DECIMAL(17, 6)           NOT NULL,
  quantity                  INTEGER                  NOT NULL,
  minimal_quantity          INTEGER                  NOT NULL,
  low_stock_threshold       INTEGER,
  low_stock_alert           BOOLEAN                  NOT NULL,
  price                     DECIMAL(20, 6)           NOT NULL,
  wholesale_price           DECIMAL(20, 6)           NOT NULL,
  unity                     CHARACTER VARYING(255),
  unit_price_ratio          DECIMAL(20, 6)           NOT NULL,
  additional_shipping_cost  DECIMAL(20, 2)           NOT NULL,
  reference                 CHARACTER VARYING(32),
  supplier_reference        CHARACTER VARYING(32),
  location                  CHARACTER VARYING(64),
  width                     DECIMAL(20, 6)           NOT NULL,
  height                    DECIMAL(20, 6)           NOT NULL,
  depth                     DECIMAL(20, 6)           NOT NULL,
  weight                    DECIMAL(20, 6)           NOT NULL,
  out_of_stock              INTEGER                  NOT NULL,
  additional_delivery_times BOOLEAN                  NOT NULL,
  quantity_discount         INTEGER,
  customizable              INTEGER                  NOT NULL,
  uploadable_files          INTEGER                  NOT NULL,
  text_fields               INTEGER                  NOT NULL,
  active                    BOOLEAN                  NOT NULL,
  redirect_type             CHARACTER VARYING(255)   NOT NULL,
  id_type_redirected        CHAVE                    NOT NULL,
  available_for_order       BOOLEAN                  NOT NULL,
  available_date            TIMESTAMP WITH TIME ZONE,
  show_condition            BOOLEAN                  NOT NULL,
  condition                 CHARACTER VARYING(255)   NOT NULL,
  show_price                BOOLEAN                  NOT NULL,
  indexed                   BOOLEAN                  NOT NULL,
  visibility                CHARACTER VARYING(255)   NOT NULL,
  cache_is_pack             BOOLEAN                  NOT NULL,
  cache_has_attachments     BOOLEAN                  NOT NULL,
  is_virtual                BOOLEAN                  NOT NULL,
  cache_default_attribute   BOOLEAN,
  date_add                  TIMESTAMP WITH TIME ZONE NOT NULL,
  date_upd                  TIMESTAMP WITH TIME ZONE NOT NULL,
  advanced_stock_management BOOLEAN                  NOT NULL,
  pack_stock_type           BOOLEAN                  NOT NULL,
  state                     BOOLEAN                  NOT NULL,
  CONSTRAINT pk_product PRIMARY KEY (id)
);