CREATE TABLE orders (
  id                       CHAVE                    NOT NULL,
  reference                CHARACTER VARYING(9),
  id_shop_group            CHAVE                    NOT NULL,
  id_shop                  CHAVE                    NOT NULL,
  id_carrier               CHAVE                    NOT NULL,
  id_lang                  CHAVE                    NOT NULL,
  id_customer              CHAVE                    NOT NULL,
  id_cart                  CHAVE                    NOT NULL,
  id_currency              CHAVE                    NOT NULL,
  id_address_delivery      CHAVE                    NOT NULL,
  id_address_invoice       CHAVE                    NOT NULL,
  current_state            INTEGER                  NOT NULL,
  secure_key               CHARACTER VARYING(32)    NOT NULL,
  payment                  CHARACTER VARYING(255)   NOT NULL,
  conversion_rate          DECIMAL(13, 6)           NOT NULL,
  module                   CHARACTER VARYING(255),
  recyclable               BOOLEAN                  NOT NULL,
  gift                     BOOLEAN                  NOT NULL,
  gift_message             TEXT,
  mobile_theme             BOOLEAN                  NOT NULL,
  shipping_number          CHARACTER VARYING(64),
  total_discounts          DECIMAL(20, 6)           NOT NULL,
  total_discounts_tax_incl DECIMAL(20, 6)           NOT NULL,
  total_discounts_tax_excl DECIMAL(20, 6)           NOT NULL,
  total_paid               DECIMAL(20, 6)           NOT NULL,
  total_paid_tax_incl      DECIMAL(20, 6)           NOT NULL,
  total_paid_tax_excl      DECIMAL(20, 6)           NOT NULL,
  total_paid_real          DECIMAL(20, 6)           NOT NULL,
  total_products           DECIMAL(20, 6)           NOT NULL,
  total_products_wt        DECIMAL(20, 6)           NOT NULL,
  total_shipping           DECIMAL(20, 6)           NOT NULL,
  total_shipping_tax_incl  DECIMAL(20, 6)           NOT NULL,
  total_shipping_tax_excl  DECIMAL(20, 6)           NOT NULL,
  carrier_tax_rate         DECIMAL(10, 3)           NOT NULL,
  total_wrapping           DECIMAL(20, 6)           NOT NULL,
  total_wrapping_tax_incl  DECIMAL(20, 6)           NOT NULL,
  total_wrapping_tax_excl  DECIMAL(20, 6)           NOT NULL,
  round_mode               BOOLEAN                  NOT NULL,
  round_type               BOOLEAN                  NOT NULL,
  invoice_number           INTEGER                  NOT NULL,
  delivery_number          INTEGER                  NOT NULL,
  invoice_date             TIMESTAMP WITH TIME ZONE NOT NULL,
  delivery_date            TIMESTAMP WITH TIME ZONE NOT NULL,
  valid                    BOOLEAN                  NOT NULL,
  date_add                 TIMESTAMP WITH TIME ZONE NOT NULL,
  date_upd                 TIMESTAMP WITH TIME ZONE NOT NULL,
  CONSTRAINT pk_orders PRIMARY KEY (id)
);