CREATE TABLE supplyorderdetail (
  id                            CHAVE                  NOT NULL,
  id_supply_order               CHAVE                  NOT NULL,
  id_currency                   CHAVE                  NOT NULL,
  id_product                    CHAVE                  NOT NULL,
  id_product_attribute          CHAVE                  NOT NULL,
  reference                     CHARACTER VARYING(32)  NOT NULL,
  supplier_reference            CHARACTER VARYING(32)  NOT NULL,
  name                          CHARACTER VARYING(128) NOT NULL,
  ean13                         CHARACTER VARYING(13),
  isbn                          CHARACTER VARYING(32),
  upc                           CHARACTER VARYING(12),
  exchange_rate                 DECIMAL(20, 6),
  unit_price_te                 DECIMAL(20, 6),
  quantity_expected             INTEGER                NOT NULL,
  quantity_received             INTEGER                NOT NULL,
  price_te                      DECIMAL(20, 6),
  discount_rate                 DECIMAL(20, 6),
  discount_value_te             DECIMAL(20, 6),
  price_with_discount_te        DECIMAL(20, 6),
  tax_rate                      DECIMAL(20, 6),
  tax_value                     DECIMAL(20, 6),
  price_ti                      DECIMAL(20, 6),
  tax_value_with_order_discount DECIMAL(20, 6),
  price_with_order_discount_te  DECIMAL(20, 6),
  CONSTRAINT pk_supplyorderdetail PRIMARY KEY (id)
);