CREATE TABLE cartrule (
  id                        CHAVE                    NOT NULL,
  id_customer               CHAVE                    NOT NULL,
  date_from                 TIMESTAMP WITH TIME ZONE NOT NULL,
  date_to                   TIMESTAMP WITH TIME ZONE NOT NULL,
  description               TEXT,
  quantity                  INTEGER                  NOT NULL,
  quantity_per_user         INTEGER                  NOT NULL,
  priority                  INTEGER                  NOT NULL,
  partial_use               BOOLEAN                  NOT NULL,
  code                      CHARACTER VARYING(254)   NOT NULL,
  minimum_amount            DECIMAL(17, 2)           NOT NULL,
  minimum_amount_tax        BOOLEAN                  NOT NULL,
  minimum_amount_currency   INTEGER                  NOT NULL,
  minimum_amount_shipping   BOOLEAN                  NOT NULL,
  country_restriction       BOOLEAN                  NOT NULL,
  carrier_restriction       BOOLEAN                  NOT NULL,
  group_restriction         BOOLEAN                  NOT NULL,
  cart_rule_restriction     BOOLEAN                  NOT NULL,
  product_restriction       BOOLEAN                  NOT NULL,
  shop_restriction          BOOLEAN                  NOT NULL,
  free_shipping             BOOLEAN                  NOT NULL,
  reduction_percent         DECIMAL(5, 2)            NOT NULL,
  reduction_amount          DECIMAL(17, 2)           NOT NULL,
  reduction_tax             BOOLEAN                  NOT NULL,
  reduction_currency        INTEGER                  NOT NULL,
  reduction_product         INTEGER                  NOT NULL,
  reduction_exclude_special BOOLEAN                  NOT NULL,
  gift_product              INTEGER                  NOT NULL,
  gift_product_attribute    INTEGER                  NOT NULL,
  highlight                 BOOLEAN                  NOT NULL,
  active                    BOOLEAN                  NOT NULL,
  date_add                  TIMESTAMP WITH TIME ZONE NOT NULL,
  date_upd                  TIMESTAMP WITH TIME ZONE NOT NULL,
  CONSTRAINT pk_cartrule PRIMARY KEY (id)
);