CREATE TABLE employee (
  id                       CHAVE                    NOT NULL,
  id_profile               CHAVE                    NOT NULL,
  id_lang                  CHAVE                    NOT NULL,
  lastname                 CHARACTER VARYING(32)    NOT NULL,
  firstname                CHARACTER VARYING(32)    NOT NULL,
  email                    CHARACTER VARYING(128)   NOT NULL,
  passwd                   CHARACTER VARYING(60)    NOT NULL,
  last_passwd_gen          TIMESTAMP WITH TIME ZONE NOT NULL,
  stats_date_from          TIMESTAMP WITH TIME ZONE,
  stats_date_to            TIMESTAMP WITH TIME ZONE,
  stats_compare_from       TIMESTAMP WITH TIME ZONE,
  stats_compare_to         TIMESTAMP WITH TIME ZONE,
  stats_compare_option     BOOLEAN                  NOT NULL,
  preselect_date_range     CHARACTER VARYING(32),
  bo_color                 CHARACTER VARYING(32),
  bo_theme                 CHARACTER VARYING(32),
  bo_css                   CHARACTER VARYING(64),
  default_tab              INTEGER                  NOT NULL,
  bo_width                 INTEGER                  NOT NULL,
  bo_menu                  BOOLEAN                  NOT NULL,
  active                   BOOLEAN                  NOT NULL,
  optin                    BOOLEAN                  NOT NULL,
  id_last_order            CHAVE                    NOT NULL,
  id_last_customer_message CHAVE                    NOT NULL,
  id_last_customer         CHAVE                    NOT NULL,
  last_connection_date     TIMESTAMP WITH TIME ZONE,
  reset_password_token     CHARACTER VARYING(40),
  reset_password_validity  TIMESTAMP WITH TIME ZONE,
  CONSTRAINT pk_employee PRIMARY KEY (id)
);