CREATE TABLE customer (
  id                         CHAVE                    NOT NULL,
  id_shop_group              CHAVE                    NOT NULL,
  id_shop                    CHAVE                    NOT NULL,
  id_gender                  CHAVE                    NOT NULL,
  id_default_group           CHAVE                    NOT NULL,
  id_lang                    CHAVE,
  id_risk                    CHAVE                    NOT NULL,
  company                    CHARACTER VARYING(64),
  siret                      CHARACTER VARYING(14),
  ape                        CHARACTER VARYING(5),
  firstname                  CHARACTER VARYING(255)   NOT NULL,
  lastname                   CHARACTER VARYING(255)   NOT NULL,
  email                      CHARACTER VARYING(128)   NOT NULL,
  passwd                     CHARACTER VARYING(60)    NOT NULL,
  last_passwd_gen            TIMESTAMP WITH TIME ZONE NOT NULL,
  birthday                   TIMESTAMP WITH TIME ZONE,
  newsletter                 BOOLEAN                  NOT NULL,
  ip_registration_newsletter CHARACTER VARYING(15),
  newsletter_date_add        TIMESTAMP WITH TIME ZONE,
  optin                      BOOLEAN                  NOT NULL,
  website                    CHARACTER VARYING(128),
  outstanding_allow_amount   DECIMAL(20, 6)           NOT NULL,
  show_public_prices         BOOLEAN                  NOT NULL,
  max_payment_days           INTEGER                  NOT NULL,
  secure_key                 CHARACTER VARYING(32)    NOT NULL,
  note                       TEXT,
  active                     BOOLEAN                  NOT NULL,
  is_guest                   BOOLEAN                  NOT NULL,
  deleted                    BOOLEAN                  NOT NULL,
  date_add                   TIMESTAMP WITH TIME ZONE NOT NULL,
  date_upd                   TIMESTAMP WITH TIME ZONE NOT NULL,
  reset_password_token       CHARACTER VARYING(40),
  reset_password_validity    TIMESTAMP WITH TIME ZONE,
  CONSTRAINT pk_customer PRIMARY KEY (id)
);