CREATE TABLE carrier (
  id                   CHAVE                 NOT NULL,
  id_reference         CHAVE                 NOT NULL,
  id_tax_rules_group   CHAVE,
  name                 CHARACTER VARYING(64) NOT NULL,
  url                  CHARACTER VARYING(255),
  active               BOOLEAN               NOT NULL,
  deleted              BOOLEAN               NOT NULL,
  shipping_handling    BOOLEAN               NOT NULL,
  range_behavior       BOOLEAN               NOT NULL,
  is_module            BOOLEAN               NOT NULL,
  is_free              BOOLEAN               NOT NULL,
  shipping_external    BOOLEAN               NOT NULL,
  need_range           BOOLEAN               NOT NULL,
  external_module_name CHARACTER VARYING(64),
  shipping_method      INTEGER               NOT NULL,
  position             INTEGER               NOT NULL,
  max_width            INTEGER,
  max_height           INTEGER,
  max_depth            INTEGER,
  max_weight           DECIMAL(20, 6),
  grade                INTEGER,
  CONSTRAINT pk_carrier PRIMARY KEY (id)
);