CREATE TABLE specificprice (
  id                     CHAVE                    NOT NULL,
  id_specific_price_rule CHAVE                    NOT NULL,
  id_cart                CHAVE                    NOT NULL,
  id_product             CHAVE                    NOT NULL,
  id_shop                CHAVE                    NOT NULL,
  id_shop_group          CHAVE                    NOT NULL,
  id_currency            CHAVE                    NOT NULL,
  id_country             CHAVE                    NOT NULL,
  id_group               CHAVE                    NOT NULL,
  id_customer            CHAVE                    NOT NULL,
  id_product_attribute   CHAVE                    NOT NULL,
  price                  DECIMAL(20, 6)           NOT NULL,
  from_quantity          INTEGER                  NOT NULL,
  reduction              DECIMAL(20, 6)           NOT NULL,
  reduction_tax          BOOLEAN                  NOT NULL,
  reduction_type         CHARACTER VARYING(255)   NOT NULL,
  from_                  TIMESTAMP WITH TIME ZONE NOT NULL,
  to_                    TIMESTAMP WITH TIME ZONE NOT NULL,
  CONSTRAINT pk_specificprice PRIMARY KEY (id)
);