CREATE TABLE orderdetail (
  id                            CHAVE                  NOT NULL,
  id_order                      CHAVE                  NOT NULL,
  id_order_invoice              CHAVE,
  id_warehouse                  CHAVE,
  id_shop                       CHAVE                  NOT NULL,
  product_id                    CHAVE                  NOT NULL,
  product_attribute_id          CHAVE,
  id_customization              CHAVE,
  product_name                  CHARACTER VARYING(255) NOT NULL,
  product_quantity              INTEGER                NOT NULL,
  product_quantity_in_stock     INTEGER                NOT NULL,
  product_quantity_refunded     INTEGER                NOT NULL,
  product_quantity_return       INTEGER                NOT NULL,
  product_quantity_reinjected   INTEGER                NOT NULL,
  product_price                 DECIMAL(20, 6)         NOT NULL,
  reduction_percent             DECIMAL(10, 2)         NOT NULL,
  reduction_amount              DECIMAL(20, 6)         NOT NULL,
  reduction_amount_tax_incl     DECIMAL(20, 6)         NOT NULL,
  reduction_amount_tax_excl     DECIMAL(20, 6)         NOT NULL,
  group_reduction               DECIMAL(10, 2)         NOT NULL,
  product_quantity_discount     DECIMAL(20, 6)         NOT NULL,
  product_ean13                 CHARACTER VARYING(13),
  product_isbn                  CHARACTER VARYING(32),
  product_upc                   CHARACTER VARYING(12),
  product_reference             CHARACTER VARYING(32),
  product_supplier_reference    CHARACTER VARYING(32),
  product_weight                DECIMAL(20, 6)         NOT NULL,
  id_tax_rules_group            CHAVE,
  tax_computation_method        BOOLEAN                NOT NULL,
  tax_name                      CHARACTER VARYING(16)  NOT NULL,
  tax_rate                      DECIMAL(10, 3)         NOT NULL,
  ecotax                        DECIMAL(21, 6)         NOT NULL,
  ecotax_tax_rate               DECIMAL(5, 3)          NOT NULL,
  discount_quantity_applied     BOOLEAN                NOT NULL,
  download_hash                 CHARACTER VARYING(255),
  download_nb                   INTEGER,
  download_deadline             TIMESTAMP WITH TIME ZONE,
  total_price_tax_incl          DECIMAL(20, 6)         NOT NULL,
  total_price_tax_excl          DECIMAL(20, 6)         NOT NULL,
  unit_price_tax_incl           DECIMAL(20, 6)         NOT NULL,
  unit_price_tax_excl           DECIMAL(20, 6)         NOT NULL,
  total_shipping_price_tax_incl DECIMAL(20, 6)         NOT NULL,
  total_shipping_price_tax_excl DECIMAL(20, 6)         NOT NULL,
  purchase_supplier_price       DECIMAL(20, 6)         NOT NULL,
  original_product_price        DECIMAL(20, 6)         NOT NULL,
  original_wholesale_price      DECIMAL(20, 6)         NOT NULL,
  CONSTRAINT pk_orderdetail PRIMARY KEY (id)
);