CREATE TABLE address (
  id              CHAVE                    NOT NULL,
  id_country      CHAVE                    NOT NULL,
  id_state        CHAVE,
  id_customer     CHAVE                    NOT NULL,
  id_manufacturer CHAVE                    NOT NULL,
  id_supplier     CHAVE                    NOT NULL,
  id_warehouse    CHAVE                    NOT NULL,
  alias           CHARACTER VARYING(32)    NOT NULL,
  company         CHARACTER VARYING(255),
  lastname        CHARACTER VARYING(255)   NOT NULL,
  firstname       CHARACTER VARYING(255)   NOT NULL,
  address1        CHARACTER VARYING(128)   NOT NULL,
  address2        CHARACTER VARYING(128),
  postcode        CHARACTER VARYING(12),
  city            CHARACTER VARYING(64)    NOT NULL,
  other           TEXT,
  phone           CHARACTER VARYING(32),
  phone_mobile    CHARACTER VARYING(32),
  vat_number      CHARACTER VARYING(32),
  dni             CHARACTER VARYING(16),
  date_add        TIMESTAMP WITH TIME ZONE NOT NULL,
  date_upd        TIMESTAMP WITH TIME ZONE NOT NULL,
  active          BOOLEAN                  NOT NULL,
  deleted         BOOLEAN                  NOT NULL,
  CONSTRAINT pk_address PRIMARY KEY (id)
);