CREATE TABLE productshop (
  id                        chave                    NOT NULL,
  id_product                chave                    NOT NULL,
  id_shop                   chave                    NOT NULL,
  id_category_default       chave,
  id_tax_rules_group        chave                    NOT NULL,
  on_sale                   boolean                  NOT NULL,
  online_only               boolean                  NOT NULL,
  ecotax                    decimal(17, 6)           NOT NULL,
  minimal_quantity          integer                  NOT NULL,
  low_stock_threshold       integer,
  low_stock_alert           boolean                  NOT NULL,
  price                     decimal(20, 6)           NOT NULL,
  wholesale_price           decimal(20, 6)           NOT NULL,
  unity                     character varying(255),
  unit_price_ratio          decimal(20, 6)           NOT NULL,
  additional_shipping_cost  decimal(20, 2)           NOT NULL,
  customizable              boolean                  NOT NULL,
  uploadable_files          boolean                  NOT NULL,
  text_fields               boolean                  NOT NULL,
  active                    boolean                  NOT NULL,
  redirect_type             character varying(255)   NOT NULL,
  id_type_redirected        chave                    NOT NULL,
  available_for_order       boolean                  NOT NULL,
  available_date            timestamp with time zone,
  show_condition            boolean                  NOT NULL,
  condition                 character varying(255)   NOT NULL,
  show_price                boolean                  NOT NULL,
  indexed                   boolean                  NOT NULL,
  visibility                character varying(255)   NOT NULL,
  cache_default_attribute   integer,
  advanced_stock_management boolean                  NOT NULL,
  date_add                  timestamp with time zone NOT NULL,
  date_upd                  timestamp with time zone NOT NULL,
  pack_stock_type           integer                  NOT NULL,
  CONSTRAINT pk_productshop PRIMARY KEY (id)
);